# Generated by Django 5.2.4 on 2025-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('theme', models.TextField()),
                ('presences', models.ManyToManyField(blank=True, to='presence.licence')),
            ],
        ),
    ]
