# Generated by Django 5.2.4 on 2025-07-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='presences',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='presence.licence'),
        ),
    ]
