# Generated by Django 5.2.4 on 2025-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_alter_session_presences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='presences',
            field=models.ManyToManyField(blank=True, to='presence.licence'),
        ),
    ]
