# Generated by Django 5.2.4 on 2025-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_session_checked_by_session_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='presences',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='presence.licence'),
        ),
        migrations.AlterField(
            model_name='session',
            name='theme',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom'), name='unique_nom_prenom'),
        ),
    ]
