# Generated by Django 5.2.4 on 2025-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_ville_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
