# Generated by Django 5.2.4 on 2025-07-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licences', to='presence.etablissement'),
        ),
    ]
